### ISSUE TITLE
on_dam signature change with new `error_pool_context`

### ISSUE THREAD

**Issue by anlek** [apneadiving/waterfall#16]
Hey,
I recently updated your gem and saw the new `error_pool_context`, which is super great as I actually hit the issue of too many flows and unknown which one dammed without setting up complex error_pool setups. However, the `on_dam` signature changed from `error_pool, outflow, root` to `error_pool, error_pool_context, outflow, root`. This requires me to change 25 files and over 40+ instances in my code to make the new version work. This make me a bit worried of introduction of bugs with that many changes. 

Anyway to modify the `on_dam` that would not change the signature? aka `error_pool, outflow, root, error_pool_context` or inside `root` you could access `root.error_pool_context`?

Thanks again for all the great work!

**Comment by apneadiving** [comment]
Hi Andrew, this is embarrassing 😅
I was pretty much convinced no one used params from `on_dam` except the `error_pool` (based on few testimonials, it made sense).

Making the change was of course arbitrary as I was kind of prioritising the variables. Now it has been implemented, changing it would cause troubles for others and would also lead to confusion 😕

I am sorry to tell, but because of the aforementioned reasons, I can not change this now. I am sincerely sorry it causes troubles in your codebase. I understand many changes are uncomfortable 😔

On a more positive note, I am glad you get why it was needed/helpful to add the context. I wish I could help you more, I would gladly review the pull request but well... repo rights 😅

Best, 

Benjamin

**Comment by anlek** [comment]
Hey Benjamin,
No worries, it's not the end of the world. 
I almost pushed my code with version 1.3 of Waterfall (without proper testing 😖) and happen to over hear a co-worker talk about the `on_dam` method call, which reminded me of the new context and reviewing it I figured out the problem this would be!

I think adding a note somewhere (changelog or readme) of this breaking change might be good idea. 

I'll close this ticket for now.

**Comment by apneadiving** [comment]
It is already in the changelog 😉
Thanks for your understanding!

**Comment by anlek** [comment]
hehe, I see it now, however, it doesn't jump out at you. Maybe something like:

**BREAKING CHANGE**: `on_dam` signature changed from `error_pool, outflow, root` to `error_pool, error_pool_context, outflow, root` to support the new `error_pool_context`.
