### ISSUE TITLE
Failure within the chain

### ISSUE THREAD

**Issue by bypotatoes** [apneadiving/waterfall#8]
Hello, is there an ability to rollback previous services from call chain, e.g. similar to interactor gem?

Current docs don't have mentions such ability, but I just found it as part of your [earlier presentation](http://slides.com/apneadiving/service-objects-waterfall-rails#/8/5).

Thanks

**Comment by apneadiving** [comment]
Hi Ilya,

Could you please tel me what you want to rollback? Database insert?

Benjamin

**Comment by bypotatoes** [comment]
No, for db your example with transaction is clear. My particular case is about stripe payment:

At first I want to do external call `stripe_charge = Stripe::Charge.create(stripe_charge_params)`, since it's the least failsafe(not enough money or something like this) and than save payment to db, so if something went wrong with saving phase I'd like to refund `stripe_charge`

**Comment by apneadiving** [comment]
Ok :) what about adding this in a `on_dam` ?

**Comment by bypotatoes** [comment]
That will work, but I guess it'd be better to place rollback logic to stripe charge subchain/service or to metaservice. Is it a way to propagate error to top of chain and catch it there? I suppose it's quite similar to what Interceptor gem does

**Comment by apneadiving** [comment]
These are super interesting discussions :)

What is tricky when you start using service objects is that they are supposed to be self contained.
Why not creating your own service object to handle the rollback of, but you would rather call it from the service where the charge is created, in the `on_dam` as we saw.

This should answer your short term need.

----

I understand the need for the `rollback`, it is very convenient. I am not sure I like the interactor's approach for it but I get it. I even did code it https://github.com/apneadiving/waterfall/tree/promises_syntax but I ditched it some time after.

A `rollback` would currently clash with the `undam` method provided: if the service was dammed then undammed, then should it be rolled back? what about sub services?
I am in the middle of considering to remove `undam` because it can lead people to undesired situations. 

What is your take about it?

**Comment by apneadiving** [comment]
Here is an implementation, it is named `reverse_flow`. I have to think about it a little more.

https://github.com/apneadiving/waterfall/pull/9

**Comment by apneadiving** [comment]
I've released 1.2.0, where you have `reverse_flow`.
I have written a quick explanation here: https://github.com/apneadiving/waterfall#undo

The main benefit is whenever you have cases like:

```ruby
def call
  chain { Service1.new }
  chain { Service2.new }
  on_dam { }
end
```
if `Service2` fails, it opens the door to undo things in `Service1`.

All good for you?

**Comment by bypotatoes** [comment]
It seems great, that's what I've mentioned. Thanks for you efforts

**Comment by apneadiving** [comment]
cool I guess I can close the issue then :)
